language: ruby
rvm:
  - 2.1.1
addons:
  postgresql: "9.3"
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script: bundle exec rspec
notifications:
  email: false
env:
  - DIGITAL_OCEAN_ACCESS_TOKEN=NOPE
