source "http://rubygems.org"

ruby "2.1.1"
gem "rails", "4.1.0"

gem "awesome_print"
gem "barge"
gem "boinc_drone"
gem "bourbon"
gem "cancan"
gem "coffee-rails"
gem "delayed_job_active_record"
gem "devise"
gem "erubis"
gem "ember-rails"
gem "ember-source"
gem "font-awesome-sass"
gem "jquery-rails"
gem "local_time"
gem "neat", "~> 1.5.0"
gem "net-ssh"
gem "newrelic_rpm"
gem "omniauth-facebook"
gem "pg"
gem "puma"
gem "rename"
gem "roadie"
gem "roadie-rails"
gem "sass-rails", "~> 4.0.2"
gem "slim"
gem "sshkey"
gem "uglifier"

group :development, :test do
  gem "better_errors"
  gem "binding_of_caller"
  gem "dotenv-rails"
  gem "factory_girl_rails"
  gem "foreman"
  gem "letter_opener"
  gem "quiet_assets"
  gem "rspec-rails"
  gem "spring"
  gem "teaspoon"
end

group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "faker"
  gem "guard"
  gem "guard-rspec"
  gem "guard-teaspoon"
  gem "rb-fsevent"
  gem "terminal-notifier-guard"
  gem "vcr"
  gem "webmock"
end

group :production do
  gem "rails_12factor"
end
